services:
  - type: web
    name: gmlweb
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: nandu
      - key: ADMIN_PASSWORD
        value: Mkan@6767
      - key: PING_INTERVAL
        value: "15"
      - key: KEEP_ALIVE_ENABLED
        value: "true"
      - key: DATABASE_URL
        value: postgresql://postgres.bqoszyelbcxrqojvutva:vlwBjAOpbOFUXT7G@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
      - key: SUPABASE_URL
        value: https://bqoszyelbcxrqojvutva.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_zujftvHxzH1EuxAXwc9RRA_62_6kRUC
      - key: SUPABASE_BUCKET
        value: gml-media
      - key: MAIL_ENABLED
        value: "true"
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        value: nethrapalmjali21@gmail.com
      - key: MAIL_PASSWORD
        value: wzaziqufonusdtmu
      - key: MAIL_SENDER_NAME
        value: "GM League Season 4"
      - key: MAIL_SENDER_EMAIL
        value: nethrapalmjali21@gmail.com
